name: Release
on:
  push:
    tags:
      - '*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.19'
      - name: Build
        run: |
          make windows_64 & make windows_32 \
          & make linux_64 & make linux_32 \
          & make darwin & make arm \
          && chmod +x ./out/*
      - name: Upload Release Asset
        run: |
          set -x
          assets=()
          for asset in ./out/*; do
            assets+=("-a" "$asset")
          done
          tag_name="${GITHUB_REF##*/}"
          hub release create "${assets[@]}" -m "$tag_name" "$tag_name"